code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension JakeBecker.elixir-ls
code --install-extension James-Yu.latex-workshop
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension julialang.language-julia
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension pgourlain.erlang
code --install-extension phoenixframework.phoenix
code --install-extension rebornix.ruby
code --install-extension sianglim.slim
code --install-extension sjhuangx.vscode-scheme
code --install-extension twxs.cmake
code --install-extension wingrunr21.vscode-ruby
code --install-extension wraith13.wandbox-vscode
